# Generated by Django 3.1 on 2020-09-03 13:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200903_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasd',
            new_name='Profile',
        ),
    ]
